/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrcamentosIdRouteImport } from './routes/orcamentos.$id'
import { Route as OrcamentosNovoRouteImport } from './routes/orcamentos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosIdRoute = OrcamentosIdRouteImport.update({
  id: '/orcamentos/$id',
  path: '/orcamentos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosNovoRoute = OrcamentosNovoRouteImport.update({
  id: '/orcamentos/novo',
  path: '/orcamentos/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/orcamentos/$id' | '/orcamentos/novo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/orcamentos/$id' | '/orcamentos/novo'
  id: '__root__' | '/' | '/orcamentos/$id' | '/orcamentos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrcamentosIdRoute: typeof OrcamentosIdRoute
  OrcamentosNovoRoute: typeof OrcamentosNovoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/$id': {
      id: '/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof OrcamentosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/novo': {
      id: '/orcamentos/novo'
      path: '/orcamentos/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof OrcamentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrcamentosIdRoute: OrcamentosIdRoute,
  OrcamentosNovoRoute: OrcamentosNovoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
